name: Continuous Integration
on: push
jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.4.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Run ESLint
        run: npm run lint
